version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - insurance-service
  app:
    container_name: insurance-graphql
    build: .
    ports:
      - 3000:3000
    expose:
      - '3000'
    env_file: 
      - .env
    volumes:
      - .:/opt/app
networks: 
  insurance-service: 
    external: true
