version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbitmq
    networks:
      - insurance-service-app
  insurance-graph:
    container_name: insurance-graphql
    build: .
    ports:
      - 4000:4000
    command:
      - bash -c 'bin/setup && rails server -b 0.0.0.0 -p 4000'
    env_file:
      - .env
    volumes:
      - .:/opt/app
    networks:
      - insurance-service-app
networks: 
  insurance-service-app:
    external: true
